name: CI for Vue.js App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Match your local Node version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build project
        run: npm run build

      # New step: Check for changes (e.g., lockfile updates)
      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected"
            echo "::set-output name=changes_detected::true"
          else
            echo "No changes detected"
            echo "::set-output name=changes_detected::false"
          fi

      # New step: Commit and push changes if detected
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git add .
          git commit -m "chore: update dependencies and build files [skip ci]"
          git push origin master
