name: Vue.js CI/CD with GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Deploy to GitHub Pages when code is pushed to master branch
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment with caching
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linter to check code quality
      - name: Run linter
        run: npm run lint

      # Step 5: Build the Vue.js project
      - name: Build project
        run: npm run build

      # Step 6: Upload `dist` folder as GitHub Pages artifact
      - name: Upload artifact for GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
